---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install NMP/ NodeJS"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update-cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create directory
  become: true
  file:
    path: /home/ubuntu/web
    state: directory
    mode: 0755

- name: copy artifact files
  become: true
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/web/artifact.tar.gz

- name: unpack backend files
  become: true
  shell: |
    cd /home/ubuntu/web
    tar -vxf artifact.tar.gz

- name: start app
  become: true
  shell: |
    cd /home/ubuntu/web
    pm2 stop default
    pm2 start npm -- start
